"use client";

import Header from "@/components/Header";
import { ThemeContext } from "@/context";
import "@/styles/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SessionProvider } from "next-auth/react";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "SuperHero Database",
//   description: "Generated by create next app",
//   icons: {
//     icon: "../../public/assets/super_favicon.png"
//   }
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState<boolean>(true); // Default to dark mode
  const [perPage, setPerPage] = useState<number>(5); // Number of items per page
  const [page, setPage] = useState<number>(1); // Current page number
  const [sortOrder, setSortOrder] = useState<string>("asc"); // 'asc' or 'desc'
  const [searchQuery, setSearchQuery] = useState<string>(""); // search query is pulled to root level to stay in back switch

  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <SessionProvider>
        <QueryClientProvider client={queryClient}>
          <ThemeContext
            value={{
              darkMode,
              setDarkMode,
              perPage,
              setPerPage,
              sortOrder,
              setSortOrder,
              page,
              setPage,
              searchQuery,
              setSearchQuery,
            }}
          >
            <body
              className={`${
                darkMode ? "dark" : ""
              } font-sans bg-white dark:bg-slate-900 transition-colors duration-300`}
            >
              <Header />
              {children}
            </body>
          </ThemeContext>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        </QueryClientProvider>
      </SessionProvider>
    </html>
  );
}
