"use client"

import Header from "@/components/Header";
import { ThemeContext } from "@/context";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "SuperHero Database",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState<boolean>(true); // Default to dark mode
  const [perPage, setPerPage] = useState<number>(5); // Number of items per page
  const [page, setPage] = useState<number>(1); // Current page number
  const [sortOrder, setSortOrder] = useState<string>("asc"); // 'asc' or 'desc'
  const [searchQuery, setSearchQuery] = useState<string>(""); // search query is pulled to root level to stay in back switch
  return (
    <html lang="en">
      <body>
        <ThemeContext
          value={{
            darkMode,
            setDarkMode,
            perPage,
            setPerPage,
            sortOrder,
            setSortOrder,
            page,
            setPage,
            searchQuery,
            setSearchQuery,
          }}
        >
          <Header />
          {children}
        </ThemeContext>
      </body>
    </html>
  );
}
